//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_BITMAP4                     162
#define IDB_ROLE1                       162
#define IDB_ROLE_TEST                   163
#define IDB_GATE1                       165
#define IDB_PNG1                        166
#define IDB_BITMAP3                     175
#define IDB_FLOOR_1                     175
#define IDB_FLOOR_TEST                  175
#define IDB_BITMAP5                     176
#define IDB_WALL_1                      176
#define IDB_CH1_0                       177
#define IDB_CH1_1                       180
#define IDB_CH1_2                       181
#define IDB_CH1_3                       182
#define IDB_CH1_4                       183
#define IDB_CH1_5                       184
#define IDB_CH1_6                       185
#define IDB_CH1_7                       186
#define IDB_CH1_8                       187
#define IDB_enemy0_0                    188
#define IDB_enemy0_1                    189
#define IDB_enemy0_2                    190
#define IDB_enemy0_3                    191
#define IDB_enemy0_4                    192
#define IDB_enemy0_5                    193
#define IDB_enemy0_die                  194
#define IDB_enemy1_0                    195
#define IDB_enemy1_1                    196
#define IDB_enemy1_2                    197
#define IDB_enemy1_3                    198
#define IDB_enemy1_4                    199
#define IDB_enemy1_5                    200
#define IDB_enemy1_die                  201
#define IDB_enemy2_0                    202
#define IDB_enemy2_1                    203
#define IDB_enemy2_2                    204
#define IDB_enemy2_3                    205
#define IDB_enemy2_4                    206
#define IDB_enemy2_5                    207
#define IDB_enemy2_6                    208
#define IDB_enemy2_7                    209
#define IDB_BITMAP15                    210
#define IDB_enemy2_die                  210
#define IDB_CH1_0_L                     211
#define IDB_CH1_1_L                     212
#define IDB_CH1_2_L                     213
#define IDB_CH1_3_L                     214
#define IDB_CH1_4_L                     215
#define IDB_CH1_5_L                     216
#define IDB_CH1_6_L                     217
#define IDB_BITMAP13                    218
#define IDB_CH1_7_L                     218
#define IDB_weapon1                     219
#define IDB_BITMAP7                     220
#define IDB_weapon1_l                   220
#define IDB_Bullet1                     221
#define IDB_Bullet_e                    222
#define IDB_Bullet2                     223
#define IDB_BITMAP10                    224
#define IDB_Bullet3                     224
#define IDB_Bullet0                     225
#define IDB_BITMAP6                     226
#define IDB_TREASURE_0_0                226
#define IDB_BITMAP8                     227
#define IDB_BITMAP9                     228
#define IDB_BITMAP11                    229
#define IDB_BITMAP12                    230
#define IDB_BITMAP14                    231
#define IDB_BITMAP16                    232
#define IDB_BITMAP17                    233
#define IDB_BITMAP18                    234
#define IDB_BITMAP19                    235
#define IDB_BITMAP20                    236
#define IDB_BITMAP21                    237
#define IDB_BITMAP22                    238
#define IDB_BITMAP23                    239
#define IDB_BITMAP24                    240
#define IDB_BITMAP25                    241
#define IDB_BITMAP26                    242
#define IDB_BITMAP27                    243
#define IDB_BITMAP28                    244
#define IDB_BITMAP29                    245
#define IDB_ENEMY0_4_L                  246
#define IDB_ENEMY0_0_L                  247
#define IDB_enemy0_0_                   247
#define IDB_CH1_DIE                     248
#define IDB_ENEMY0_1_L                  249
#define IDB_ENEMY0_2_L                  250
#define IDB_ENEMY0_3_L                  251
#define IDB_BITMAP31                    253
#define IDB_enemy0_1_                   253
#define IDB_BITMAP32                    254
#define IDB_BITMAP33                    255
#define IDB_BITMAP34                    256
#define IDB_BITMAP35                    257
#define IDB_BITMAP36                    258
#define IDB_BITMAP37                    259
#define IDB_BITMAP38                    260
#define IDB_BITMAP39                    261
#define IDB_BITMAP40                    262
#define IDB_BITMAP41                    263
#define IDB_BITMAP42                    264
#define IDB_BITMAP43                    265
#define IDB_BITMAP44                    266
#define IDB_BITMAP45                    267
#define IDB_BITMAP46                    268
#define IDB_BITMAP47                    269
#define IDB_BITMAP48                    270
#define IDB_BITMAP49                    271
#define IDB_Wall0                       272
#define IDB_Wall1                       273
#define IDB_BITMAP51                    274
#define IDB_Wall2                       274
#define IDB_ENEMY0_5_L                  280
#define IDB_ENEMY1_0_L                  281
#define IDB_ENEMY1_1_L                  282
#define IDB_ENEMY1_2_L                  283
#define IDB_ENEMY1_3_L                  284
#define IDB_ENEMY1_4_L                  285
#define IDB_ENEMY1_5_L                  286
#define IDB_ENEMY2_0_L                  287
#define IDB_ENEMY2_1_L                  288
#define IDB_ENEMY2_2_L                  289
#define IDB_ENEMY2_3_L                  290
#define IDB_ENEMY2_4_L                  291
#define IDB_ENEMY2_5_L                  292
#define IDB_ENEMY2_6_L                  293
#define IDB_BITMAP69                    294
#define IDB_ENEMY2_7_L                  294
#define IDB_BITMAP30                    295
#define IDB_UI_HP                       295
#define IDB_Floor_0_0                   305
#define IDB_floor_0_1                   307
#define IDB_Floor_0_2                   308
#define IDB_Floor_0_3                   309
#define IDB_Floor_0_4                   310
#define IDB_Floor_0_5                   311
#define IDB_Wall_0_1                    312
#define IDB_Wall_0_0                    313
#define IDB_Slash                       314
#define IDB_UI_HPBar                    315
#define IDB_UI_SPBar                    316
#define IDB_UI_MPBar                    317
#define IDB_TransferGate_0              322
#define IDB_TransferGate_1              325
#define IDB_TransferGate_2              326
#define IDB_TransferGate_3              327
#define IDB_TransferGate_4              328
#define IDB_TransferGate_5              329
#define IDB_TransferGate_6              330
#define IDB_TransferGate_7              331
#define IDB_BITMAP50                    332
#define IDB_weapon_0_0                  332
#define IDB_weapon_0_180                333
#define IDB_ItemArrow_0                 334
#define IDB_ItemArrow_1                 335
#define IDB_ItemArrow_2                 336
#define IDB_ItemArrow_3                 337
#define IDB_ItemArrow_4                 338
#define IDB_ItemArrow_5                 339
#define IDB_BITMAP52                    340
#define IDB_TREASURE_0_top              341
#define IDB_TREASURE_0_left             342
#define IDB_BITMAP53                    343
#define IDB_TREASURE_0_right            343
#define IDB_Wall_0_WallBottom           344
#define IDB_AISLEWALL_0                 345
#define IDB_AISLEWALL_PILLAR_0          346
#define IDB_AISLEWALL_PILLAR_1          347
#define IDB_AISLEWALL_PILLAR_2          348
#define IDB_AISLEWALL_PILLAR_3          349
#define IDB_AISLEWALL_PILLAR_4          350
#define IDB_BITMAP54                    351
#define IDB_AISLEWALL_PILLAR_5          351
#define IDB_TREASURE_0_1                352
#define IDB_TREASURE_0_2                353
#define IDB_TREASURE_0_3                354
#define IDB_weapon_0_90                 355
#define IDB_BITMAP56                    356
#define IDB_weapon_0_270                356
#define IDB_MinMap_NOTEXPLORED          357
#define IDB_MinMap_Playerin             358
#define IDB_MinMap_EXPLORED             359
#define IDB_MinMap_INIT                 360
#define IDB_MinMap_TREASURE             361
#define IDB_MinMap_END                  362
#define IDB_MinMap_AILSEH               363
#define IDB_MinMap_AILSES               364
#define IDB_MinMap_BOSS                 365
#define IDB_gold_1_0                    366
#define IDB_gold_0                      367
#define IDB_gold_1_1                    368
#define IDB_gold_1_2                    369
#define IDB_gold_1_3                    370
#define IDB_energyBall_0                371
#define IDB_MinMap_SPECIAL              372
#define IDB_REDPOTION_0                 373
#define IDB_REDPOTION_1                 374
#define IDB_BULEPOTION_0                375
#define IDB_BULEPOTION_1                376
#define IDB_playerAppearance_0          377
#define IDB_playerAppearance_1          378
#define IDB_playerAppearance_2          379
#define IDB_playerAppearance_3          380
#define IDB_BITMAP55                    381
#define IDB_playerAppearance_4          381
#define IDB_Homepage                    382
#define IDB_Homepage_title              383
#define IDB_start0                      384
#define IDB_start1                      385
#define IDB_start2                      386
#define IDB_start3                      387
#define IDB_start4                      388
#define IDB_start5                      389
#define IDB_start6                      390
#define IDB_start7                      391
#define IDB_newgame0                    392
#define IDB_newgame1                    393
#define IDB_gamenote0                   394
#define IDB_gamenote1                   395
#define IDB_BITMAP57                    396
#define IDB_note_test                   396
#define IDB_BTN_pause_0                 397
#define IDB_BTN_pause_1                 398
#define IDB_BTN_continue_0              399
#define IDB_BTN_continue_1              400
#define IDB_BTN_goback_0                401
#define IDB_BITMAP59                    402
#define IDB_BTN_goback_1                402
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        403
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
